[package]
name = "secrets"
version = "0.1.0"
authors = ["David King <dking@ketralnis.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.7.14"

[dependencies]
clap = "2.9.2"
rusqlite = "0.7.3"
sodiumoxide = "0.0.12"
openssl = "0.7.13"
regex = "0.1.71"
quick-error = "1.1.0"
log = "0.3.6"
env_logger = "0.3.3"
rpassword = "0.2.2"
byteorder = "0.5"
tempdir = "0.3"
tempfile = "2.1.4"
rustc-serialize = "0.3.19"
serde = "0.7.8"
serde_json = "0.7.4"
time = "0.1"
url = "1.0"

[dependencies.hyper]
version = "0.9.7"
features = ["openssl"]
